# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 16:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='speaker_notes',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
