# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_auto_20160513_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='centered_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='display_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='display_weaver',
            field=models.BooleanField(default=False),
        ),
    ]
