# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_auto_20160513_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
